#!/bin/bash

user="hobson-tv"

i=0

while [  $i -lt 25 ]; do
	let offset=i*20
	echo $offset
	curl https://api.scratch.mit.edu/users/$user/projects?offset=$offset > ../files/$user\_projects_part_$i.json
	let i=i+1 
done
